### ISSUE TITLE
Main Menu Effect Bug @ 1280x1024 Resolution

### ISSUE THREAD

**Issue by Toxoid-49b** [OpenVirusTheGameTeam/Open-Virus-The-Game#2]
The main menu "flash-in" effect does not work correctly at 1280x1024 resolution. There is a small portion near the bottom of the screen where the main base is visible throughout the duration of the effect.
![issue 2](https://cloud.githubusercontent.com/assets/9778362/7108171/c9899bf8-e14b-11e4-89a8-fb9830d9297a.png)

**Comment by darkevilmac** [comment]
Mistake on my part, I'll go ahead and fix it and push.
