### ISSUE TITLE
Deleting this repo

### ISSUE THREAD

**Issue by Jan4V** [OpenVirusTheGameTeam/Open-Virus-The-Game#3]
http://www.strawpoll.me/11982415

End of poll: 1.1.2017

**Comment by Jan4V** [comment]
@Toxoid-49b @darkevilmac you are the biggest contributors, please comment on this matter.

**Comment by Jan4V** [comment]
I see a few people has voted already, if you voted, please also leave a comment either here or on reddit:
https://www.reddit.com/r/virusjam/comments/5kxr87/jan4v_here_speaking_about_the_current_state_of/

**Comment by scribblemaniac** [comment]
I just voted against this. Even if you do want to switch to another engine, I see no reason why the current code needs to be deleted. Leave this as an 'archived' repository or keep the commit history and make your changes as new commits.

**Comment by Jan4V** [comment]
Well, fair point.
I dont see a way to 'archive' a repo on github, and keeping the commit history doesnt seem to give any benefits to creating a new repo.
The ver important fact is, that currently, I am the only active owner of this repo/team. Toxoid wasnt there in the first place, while inactive people like darkevilmac and Byron Kellet were.
I removed Byron first, as his account was inactive on github since 2015.
darkevilmac was removed after, as I didnt see him communicate in any way with the team since 2015.

I just dont see the point in leaving this code and commit history on github. We can start a new one, free of stupid commits we made in 2014, in Unity or not, doesnt matter. I have some time to work on the project now. I dont know the current state of the game in this repo, however I dont think its in any good state. I would drop game engines entirely, however I dont know if others are comfortable with programing without one. But even if we use unity, it has to be structured, well organized code, with consistent code-style.

**Comment by scribblemaniac** [comment]
Fair point as well 😉 
The advantage to keeping the code somewhere is that it can serve as a useful reference. Also a lot of the assets can be reused. If you intend on reusing any of the code, then keeping the commits somewhere means that the contributors will still receive credit.

As another option, you could put the current code in a separate branch and rebase master to remove the stupid comments.

**Comment by Jan4V** [comment]
If you can tell me how to make this repo read only, I will do that instead of deleting it.
I would however like to put the new code in a new repo.
A big point of this is also to get the OG contributors to come here and contact the team.
As reddit has been pretty much the only communication channel for us, many of the members, including myself didnt see any comunication from other team members. 
The only active person for quite a while has been Toxoid. By making a new repo, I can also get more people to acknowledge the project and work on it. 
I have told many people about this project before, and the only reason they didnt contribute is because the code is very badly organized, and done. So I think starting this project from scratch is pretty much the only way to make Virus: The Game great again. I can get atleast one person to contribute to this project, if we hide the shitty commit history :).

I see you have forked the repo, presumably for archival purposes. However I would really appreciate if you deleted that, and instead, downloaded a zip. That way we can reuse the assets and can hide the history from people :).

**Comment by darkevilmac** [comment]
> can hide the history from people :).

Good luck with that, you can't really hide the history of things on the internet.

I really think the way you've gone about this is flawed, instead of doing a check in to see what the current state of the project is and contacting other devs you just immediately hid them from the project. You're not the only contributor to the project in fact you've only made 3 commits from what I can tell, one of which was just removing a batch script that was a stub for a jenkins build service.

I stopped contributing due to lack of interest and lack of time, I've gone ahead and forked the repo myself so I have the option to continue development in the future if I decide to do so.

**Comment by Jan4V** [comment]
I checked the state, and definately didnt hide the project from anyone. Everyone who was able to contribute to the project still is able to. Added you back as a owner.
